docker-compose-yaml: docker-compose.yml

project: mind-to-mine

tasks:
  post-rollout:
    - run:
        name: env variables
        command: env
        service: cli
    - run:
        name: drush deploy
        command: drush -y deploy
        service: cli

environments:
  main:
    cronjobs:
      - name: drush cron
        schedule: "H * * * *" # this will run the cron once per hour
        command: drush cron
        service: cli
    # routes:
    #   - varnish:
    #       - "domain.com"
